package adminui;

import model.dao.*;
import model.to.*;
import javax.swing.JOptionPane;
import utility.Validations;

public class AddNewBranch extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddNewBranch
     */
    public AddNewBranch() {
        initComponents();
    }
    public AddNewBranch(BranchInfoTO record){
        this();
        if (record != null){
            jtfBranchID.setText(record.getBranchid());
            jtfIFSC.setText(record.getIFSC());
            jtfAddress.setText(record.getAddress());
            jtfContact.setText(record.getContactno());
            btnAdd.setText("Update Account Information");
            setTitle("Update Account Information");
            jtfBranchID.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfBranchID = new javax.swing.JTextField();
        jtfIFSC = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jtfContact = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Branch Details");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter IFSC Code");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Branch ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Enter Address");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Enter Contact No.");

        jtfBranchID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfBranchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBranchIDActionPerformed(evt);
            }
        });
        jtfBranchID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBranchIDKeyTyped(evt);
            }
        });

        jtfIFSC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfIFSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIFSCActionPerformed(evt);
            }
        });
        jtfIFSC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIFSCKeyTyped(evt);
            }
        });

        jtfAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAddressActionPerformed(evt);
            }
        });

        jtfContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfContactActionPerformed(evt);
            }
        });
        jtfContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfContactKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add New Branch");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIFSC, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfIFSC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBranchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBranchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBranchIDActionPerformed

    private void jtfIFSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIFSCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIFSCActionPerformed

    private void jtfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddressActionPerformed

    private void jtfContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message="";    
       boolean allvalid=true;
       String branchid=jtfBranchID.getText().trim();
       if(Validations.isEmpty(branchid))
       {
       message+="Please Enter branch ID\n\n";
       allvalid=false;
       }
       String IFSC=jtfIFSC.getText().trim();
       if(Validations.isEmpty(IFSC))
       {
       message+="Please Enter IFSC Code\n\n";
       allvalid=false;
       }
       String address=jtfAddress.getText().trim();
       if(Validations.isEmpty(address))
       {
       message+="Please Enter Address in Address Box\n\n";
       allvalid=false;
       }
       String contactno=jtfContact.getText().trim();
       if(Validations.isEmpty(contactno))
       {
       message+="Please Enter Contact Number\n\n";
       allvalid=false;
       
       }else if(contactno.length() !=10){
           message="Please Enter Valid Contact Number";
           allvalid=false;
       }
       if(allvalid){
           BranchInfoTO record=new BranchInfoTO();
           record.setBranchid(branchid);
           record.setIFSC(IFSC);
           record.setAddress(address);
           record.setContactno(contactno);
           BranchInfoDAO action=new BranchInfoDAO();
           if (btnAdd.getText().contains("Add")){
             if(action.insertrecord(record)){
               message="New Branch Is Added in System Database";
           }else{
               message="Insertion Failure Due "+ action.getErrormessage();
           }
       }  else if(btnAdd.getText().contains("Update")){
           if (action.updaterecord(record)) {
                    message = "Branch Info Is Updated In Database";
                } else {
                    message = "Info Is Not Updated  Due To " + action.getErrormessage();
                }
                CommonOperations.showScreen(getDesktopPane(), new ViewBranchDetails());
                dispose();
       }
                else {
                message = "Invalid Operation";
            }
        }
       JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfBranchIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBranchIDKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfBranchIDKeyTyped

    private void jtfContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfContactKeyTyped

    private void jtfIFSCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIFSCKeyTyped
        if(!Character.isLetterOrDigit(evt.getKeyChar())){
            evt.consume();
        }
        if(Character.isLowerCase(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfIFSCKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfBranchID;
    private javax.swing.JTextField jtfContact;
    private javax.swing.JTextField jtfIFSC;
    // End of variables declaration//GEN-END:variables
}
