package adminui;

import model.dao.*;
import model.to.*;
import javax.swing.JOptionPane;
import utility.Validations;

public class AddNewCompany extends javax.swing.JInternalFrame {

    public AddNewCompany() {
        initComponents();
    }

    public AddNewCompany(CompanyInfoTO record) {
        this();
        if (record != null) {
            jtfCompanyID.setText(record.getCompanyid());
            jtfCompanyName.setText(record.getCompanyname());
            btnAdd.setText("Update Account Information");
            setTitle("Update Account Information");
            jtfCompanyID.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCompanyName = new javax.swing.JTextField();
        jtfCompanyID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Company Details");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Company ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Company Name");

        jtfCompanyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyNameActionPerformed(evt);
            }
        });
        jtfCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCompanyNameKeyTyped(evt);
            }
        });

        jtfCompanyID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCompanyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCompanyIDActionPerformed(evt);
            }
        });
        jtfCompanyID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCompanyIDKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add New Company");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCompanyID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCompanyName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyNameActionPerformed

    private void jtfCompanyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCompanyIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCompanyIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = "";
        boolean allvalid = true;
        String companyid = jtfCompanyID.getText().trim();
        if (Validations.isEmpty(companyid)) {
            message += "Please Enter Company ID\n\n";
            allvalid = false;
        }
        String companyname = jtfCompanyName.getText().trim();
        if (Validations.isEmpty(companyname)) {
            message += "Please Enter Company Name\n\n";
            allvalid = false;
        }
        if (allvalid) {
            CompanyInfoTO record = new CompanyInfoTO();
            record.setCompanyid(companyid);
            record.setCompanyname(companyname);
            CompanyInfoDAO action = new CompanyInfoDAO();
            if (btnAdd.getText().contains("Add")) {
                if (action.insertrecord(record)) {
                    message = "New Company Is Added in System Database";
                } else {
                    message = "Insertion Failure Due " + action.getErrormessage();
                }
            } else if (btnAdd.getText().contains("Update")) {
                if (action.updaterecord(record)) {
                    message = "Company Info Is Updated In Database";
                } else {
                    message = "Info Is Not Updated  Due To " + action.getErrormessage();
                }
                CommonOperations.showScreen(getDesktopPane(), new ViewCompanyDetails());
                dispose();
            } else {
                message = "Invalid Operation";
            }
        }
        JOptionPane.showMessageDialog(this, message);

    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfCompanyNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyNameKeyTyped
        if (!Character.isLetter(evt.getKeyChar())) {
            if (!Character.isWhitespace(evt.getKeyChar())) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfCompanyNameKeyTyped

    private void jtfCompanyIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCompanyIDKeyTyped
        if(!Character.isLetterOrDigit(evt.getKeyChar())){
            evt.consume();
        }
        if(Character.isLowerCase(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfCompanyIDKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCompanyID;
    private javax.swing.JTextField jtfCompanyName;
    // End of variables declaration//GEN-END:variables
}
