package adminui;

import model.dao.*;
import model.to.*;
import java.util.List;
import javax.swing.JOptionPane;
import utility.Validations;


public class AddNewAccountInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddNewAccountInfo
     */
    public AddNewAccountInfo() {
        initComponents();
        jcbBranchID.removeAllItems();
        jcbBranchID.addItem("Choose Branch ID");
        List<BranchInfoTO> Branch= new BranchInfoDAO().getAllRecord();
        if(Branch!=null && Branch.size()>=0) {
            for(BranchInfoTO BIT:Branch) {
                jcbBranchID.addItem(BIT);
            }
        }
        }
           public AddNewAccountInfo(AccountInfoTO record){
            this();  
            if(record!=null){
                jtfAccountID.setText(record.getAccountid());
                for(int i=1;i<jcbBranchID.getItemCount();i++){
                    BranchInfoTO bit=(BranchInfoTO)jcbBranchID.getItemAt(i);
                    if(bit.getBranchid().equals(record.getBranchid())){
                        jcbBranchID.setSelectedIndex(i);
                        break;
                    }
                }
                                                                    
                jtfInitialBalance.setText(String.valueOf(record.getInitial_balance()));
                jtfCurrentBalance.setText(String.valueOf(record.getCurrent_balance()));
                jtfName.setText(record.getName());
                jtfFatherName.setText(record.getFathername());
                jtfContact.setText(record.getContactno());
                jtfAddress.setText(record.getAddress());
                btnAdd.setText("Update Account Information");
                setTitle("Update Account Information");
                jtfAccountID.setEditable(false);
            }
           }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfAccountID = new javax.swing.JTextField();
        jtfInitialBalance = new javax.swing.JTextField();
        jtfCurrentBalance = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        jtfFatherName = new javax.swing.JTextField();
        jtfContact = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        cdpOpDate = new adminui.CurrentDatePanel();
        cdpDOB = new adminui.CurrentDatePanel();
        jcbBranchID = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Account Details");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Account ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Enter Branch ID");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Enter Opening Date");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Enter Initial Balance");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Enter Current Balance");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Enter Name");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Enter Father Name");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Enter Contact No.");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Enter Date Of Birth");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Enter Address");

        jtfAccountID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfAccountID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAccountIDActionPerformed(evt);
            }
        });
        jtfAccountID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAccountIDKeyTyped(evt);
            }
        });

        jtfInitialBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfInitialBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfInitialBalanceActionPerformed(evt);
            }
        });
        jtfInitialBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfInitialBalanceKeyTyped(evt);
            }
        });

        jtfCurrentBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCurrentBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCurrentBalanceActionPerformed(evt);
            }
        });
        jtfCurrentBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCurrentBalanceKeyTyped(evt);
            }
        });

        jtfName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });
        jtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNameKeyTyped(evt);
            }
        });

        jtfFatherName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFatherNameActionPerformed(evt);
            }
        });
        jtfFatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFatherNameKeyTyped(evt);
            }
        });

        jtfContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfContactActionPerformed(evt);
            }
        });
        jtfContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfContactKeyTyped(evt);
            }
        });

        jtfAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAddressActionPerformed(evt);
            }
        });
        jtfAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAddressKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add New Account ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jcbBranchID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbBranchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBranchIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfAccountID)
                    .addComponent(jtfInitialBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(jtfCurrentBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(jtfFatherName, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(jtfContact, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .addComponent(cdpDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBranchID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cdpOpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbBranchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cdpOpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfInitialBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cdpDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfContact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAccountIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAccountIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAccountIDActionPerformed

    private void jtfAccountIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAccountIDKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfAccountIDKeyTyped

    private void jtfInitialBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfInitialBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInitialBalanceActionPerformed

    private void jtfInitialBalanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfInitialBalanceKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfInitialBalanceKeyTyped

    private void jtfCurrentBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCurrentBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCurrentBalanceActionPerformed

    private void jtfCurrentBalanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCurrentBalanceKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfCurrentBalanceKeyTyped

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    private void jtfNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNameKeyTyped
        if(!Character.isLetter(evt.getKeyChar())){
            if(!Character.isWhitespace(evt.getKeyChar())){
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfNameKeyTyped

    private void jtfFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFatherNameActionPerformed

    private void jtfFatherNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFatherNameKeyTyped
        if(!Character.isLetter(evt.getKeyChar())){
            if(!Character.isWhitespace(evt.getKeyChar())){
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfFatherNameKeyTyped

    private void jtfContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContactActionPerformed

    private void jtfContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfContactKeyTyped

    private void jtfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddressActionPerformed

    private void jtfAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAddressKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         String message="";    
       boolean allvalid=true;
       String accountid=jtfAccountID.getText().trim();
       if(Validations.isEmpty(accountid))
       {
       message+="Please Enter account ID\n\n";
       allvalid=false;
       }
       if(jcbBranchID.getSelectedIndex()==0) {
           message+="Please Choose Any Branch ID";
           allvalid=false;
       }
       String ibalance=jtfInitialBalance.getText().trim();
       if(Validations.isEmpty(ibalance))
       {
       message+="Please Enter Initial Balance\n\n";
       allvalid=false;
       }
       String cbalance=jtfCurrentBalance.getText().trim();
       if(Validations.isEmpty(cbalance))
       {
       message+="Please Enter Current Balance\n\n";
       allvalid=false;
       }
       String name=jtfName.getText().trim();
       if(Validations.isEmpty(name))
       {
       message+="Please Enter Name In Name Box\n\n";
       allvalid=false;
       }
       String fathername=jtfFatherName.getText().trim();
       if(Validations.isEmpty(fathername))
       {
       message+="Please Enter Father Name \n\n";
       allvalid=false;
       }
       String contact=jtfContact.getText().trim();
       if(Validations.isEmpty(contact))
       {
       message+="Please Enter Contact No. \n\n";
       allvalid=false;
       }
       else if(contact.length()!=10){
           message+="Please Enter Valid Contact No. \n\n";
           allvalid=false;
       }
       String address=jtfAddress.getText().trim();
       if(Validations.isEmpty(address))
       {
       message+="Please Enter Address \n\n";
       allvalid=false;
       }
       if(cdpDOB.getSelectedDate()==null) {
           message+="Please Choose Any Date Of birth \n\n";
           allvalid=false;
       }
       if(cdpOpDate.getSelectedDate()==null) {
           message+="Please Choose Account Opened Date \n\n";
           allvalid=false;
       }
       if(allvalid) {
            AccountInfoTO record=new AccountInfoTO();
            BranchInfoTO bit=(BranchInfoTO) jcbBranchID.getSelectedItem();
            record.setAccountid(accountid);   
            record.setBranchid(bit.getBranchid());
            record.setOpeningdate(cdpOpDate.getSelectedDate());
            record.setInitial_balance(Float.parseFloat(ibalance));
            record.setCurrent_balance(Float.parseFloat(cbalance));
            record.setName(name);
            record.setFathername(fathername);
            record.setDob(cdpDOB.getSelectedDate());
            record.setContactno(contact);
            record.setAddress(address);
            AccountInfoDAO action=new AccountInfoDAO();
            if(btnAdd.getText().contains("Add")){
            if(action.insertrecord(record)) {
                message="Account Info Is Added In Database";
            }else{
                message="Info Is Not Added Due To"+action.getErrormessage();
            }
           }else if(btnAdd.getText().contains("Update")) {
               if(action.updaterecord(record)) {
                message="Account Info Is Updated In Database";
            }else{
                message="Info Is Not Updated  Due To"+action.getErrormessage();
            }
               CommonOperations.showScreen(getDesktopPane(), new ViewAccountInfo());
               dispose();
           }else{
               message="Invalid Operation";
                       
           }
       }
       
       JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jcbBranchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBranchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBranchIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private adminui.CurrentDatePanel cdpDOB;
    private adminui.CurrentDatePanel cdpOpDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jcbBranchID;
    private javax.swing.JTextField jtfAccountID;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfContact;
    private javax.swing.JTextField jtfCurrentBalance;
    private javax.swing.JTextField jtfFatherName;
    private javax.swing.JTextField jtfInitialBalance;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
}
