package adminui;

import model.dao.*;
import model.to.*;
import java.util.List;
import javax.swing.JOptionPane;
import utility.Validations;

public class AddNewTransaction extends javax.swing.JInternalFrame {

    private int transactionid;

    public AddNewTransaction() {
        initComponents();
        jcbAccountID.removeAllItems();
        jcbAccountID.addItem("Choose Account ID");
        List<AccountInfoTO> accid = new AccountInfoDAO().getAllRecord();
        if (accid != null && accid.size() >= 0) {
            for (AccountInfoTO AIT : accid) {
                jcbAccountID.addItem(AIT);

            }
        }
    }

    public AddNewTransaction(TransactionInfoTO record) {
        this();
        if (record != null) {
            this.transactionid = record.getTransactionid();
            jtfAmount.setText(String.valueOf(record.getAmount()));
            for (int i = 1; i < jcbAccountID.getItemCount(); i++) {
                AccountInfoTO pit = (AccountInfoTO) jcbAccountID.getItemAt(i);
                if (pit.getAccountid().equals(record.getAccountid())) {
                    jcbAccountID.setSelectedIndex(i);
                    break;
                }
            }
            jtfDescription.setText(record.getDescription());
            btnAdd.setText("Update Account Information");
            setTitle("Update Account Information");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfAmount = new javax.swing.JTextField();
        cdpTransactionDate = new adminui.CurrentDatePanel();
        jtfDescription = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jcbAccountID = new javax.swing.JComboBox();
        jrbCredit = new javax.swing.JRadioButton();
        jrbDebit = new javax.swing.JRadioButton();
        jrbYes = new javax.swing.JRadioButton();
        jrbNo = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Transaction Details");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Amount");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Account ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Enter Transaction Date");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Enter Transaction Type");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Enter Description");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Enter Isapprove Status");

        jtfAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAmountActionPerformed(evt);
            }
        });
        jtfAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAmountKeyTyped(evt);
            }
        });

        jtfDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescriptionActionPerformed(evt);
            }
        });
        jtfDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDescriptionKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add Transaction Details");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jcbAccountID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(jrbCredit);
        jrbCredit.setText("Credit");
        jrbCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCreditActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbDebit);
        jrbDebit.setText("Debit");

        buttonGroup2.add(jrbYes);
        jrbYes.setText("Yes");

        buttonGroup2.add(jrbNo);
        jrbNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cdpTransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jcbAccountID, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbCredit)
                        .addGap(113, 113, 113)
                        .addComponent(jrbDebit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbYes)
                        .addGap(130, 130, 130)
                        .addComponent(jrbNo)))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cdpTransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrbCredit)
                    .addComponent(jrbDebit))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jrbYes)
                    .addComponent(jrbNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jtfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAmountActionPerformed

    private void jtfAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAmountKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jtfAmountKeyTyped

    private void jtfDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescriptionActionPerformed

    private void jtfDescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescriptionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescriptionKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = "";
        boolean allvalid = true;
        String amnt = jtfAmount.getText().trim();
        if (buttonGroup1.getSelection() == null) {
            message += "Please Select Any Transaction Type\n\n";
            allvalid = false;
        }
        if (buttonGroup2.getSelection() == null) {
            message += "Please Select Any Isapprove Status\n\n";
            allvalid = false;
        }
        if (Validations.isEmpty(amnt)) {
            message += "Please Enter Amount\n\n";
            allvalid = false;
        }
        if (jcbAccountID.getSelectedIndex() == 0) {
            message += "Please Choose Any Account ID\n\n";
            allvalid = false;
        }
        String description = jtfDescription.getText().trim();
        if (Validations.isEmpty(description)) {
            message += "Please Enter Description\n\n";
            allvalid = false;
        }
        if (cdpTransactionDate.getSelectedDate() == null) {
            message += "Please Choose Transaction Date \n\n";
            allvalid = false;
        }
        if (allvalid) {
            TransactionInfoTO record = new TransactionInfoTO();
            AccountInfoTO ait = (AccountInfoTO) jcbAccountID.getSelectedItem();
            record.setAmount(Float.parseFloat(amnt));
            record.setAccountid(ait.getAccountid());
            record.setTransactiondate(cdpTransactionDate.getSelectedDate());
            record.setTransactiontype(jrbCredit.getText());
            record.setTransactiontype(jrbDebit.getText());
            record.setDescription(description);
            record.setIsapprove(jrbYes.getText());
            record.setIsapprove(jrbNo.getText());
            TransactionInfoDAO action = new TransactionInfoDAO();
            if (btnAdd.getText().contains("Add")) {
                if (action.insertrecord(record)) {
                    message = "Information Is Successfully Added In Database";
                } else {
                    message = "Info Is Not Added Due To" + action.getErrormessage();
                }
            } else if (btnAdd.getText().contains("Update")) {
                record.setTransactionid(transactionid);
                if (action.updaterecord(record)) {
                    message = "Transaction Info Is Updated In Database";
                } else {
                    message = "Info Is Not Updated  Due To " + action.getErrormessage();
                }
                CommonOperations.showScreen(getDesktopPane(), new ViewTransactionDetails());
                dispose();
            } else {
                message = "Invalid Operation";
            }

        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jrbCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCreditActionPerformed

    }//GEN-LAST:event_jrbCreditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private adminui.CurrentDatePanel cdpTransactionDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jcbAccountID;
    private javax.swing.JRadioButton jrbCredit;
    private javax.swing.JRadioButton jrbDebit;
    private javax.swing.JRadioButton jrbNo;
    private javax.swing.JRadioButton jrbYes;
    private javax.swing.JTextField jtfAmount;
    private javax.swing.JTextField jtfDescription;
    // End of variables declaration//GEN-END:variables
}
