package adminui;
import model.dao.*;
import model.to.*;
import javax.swing.JOptionPane;
import utility.Validations;

public class AddNewAccountType extends javax.swing.JInternalFrame {

    public AddNewAccountType() {
        initComponents();
    }
    public AddNewAccountType(AccountTypeTO record){
        this();  
            if(record!=null){
                jtfAccountTypeID.setText(record.getTypeid());
                jtfAccountTypeName.setText(record.getTypename());
                jtfInterestRate.setText(String.valueOf(record.getInterestrate()));
                jtfMinimum.setText(String.valueOf(record.getMinimum()));
                btnAdd.setText("Update Account Information");
                setTitle("Update Account Information");
                jtfAccountTypeID.setEditable(false);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfAccountTypeName = new javax.swing.JTextField();
        jtfInterestRate = new javax.swing.JTextField();
        jtfAccountTypeID = new javax.swing.JTextField();
        jtfMinimum = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add New Account Type Details");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Enter Account Type Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Enter Account Type ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Enter Interest Rate");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Enter Minimum");

        jtfAccountTypeName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfAccountTypeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAccountTypeNameKeyTyped(evt);
            }
        });

        jtfInterestRate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfInterestRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfInterestRateActionPerformed(evt);
            }
        });
        jtfInterestRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfInterestRateKeyTyped(evt);
            }
        });

        jtfAccountTypeID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfAccountTypeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAccountTypeIDActionPerformed(evt);
            }
        });
        jtfAccountTypeID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfAccountTypeIDKeyTyped(evt);
            }
        });

        jtfMinimum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfMinimum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMinimumActionPerformed(evt);
            }
        });
        jtfMinimum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMinimumKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAdd.setText("Add New Account Type");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAccountTypeID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAccountTypeName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAccountTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfAccountTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfInterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfInterestRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfInterestRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInterestRateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         String message="";     
          boolean allvalid=true;
        String typeid=jtfAccountTypeID.getText().trim();
       if(Validations.isEmpty(typeid)){
           message+="Please Enter Account Type ID\n\n";
       allvalid=false;
       }
       
       String typename=jtfAccountTypeName.getText().trim();
        if(Validations.isEmpty(typename)){
           message+="Please Enter Account Type Name\n\n";
       allvalid=false;
       }
       String interestrate=jtfInterestRate.getText().trim();
       if(Validations.isEmpty(interestrate)){
           message+="Please Enter Interest Rate\n\n";
       allvalid=false;
       }
       String minimum=jtfMinimum.getText().trim();
       if(Validations.isEmpty(minimum)){
           message+="Please Enter Minimum Amount\n\n";
       allvalid=false;
       }
       if(allvalid){
           AccountTypeTO record=new AccountTypeTO();
           record.setTypeid(typeid);
           record.setTypename(typename);
           record.setInterestrate(Float.parseFloat(interestrate));
           record.setMinimum(Float.parseFloat(minimum));
           AccountTypeDAO action =new AccountTypeDAO();
           if(btnAdd.getText().contains("Add")){
           if(action.insertrecord(record)){
               message="New Account Type Is Added in System Database";
           }else{
               message="Insertion Failure Due "+ action.getErrormessage();
           }
       }else if(btnAdd.getText().contains("Update")){
           if(action.updaterecord(record)) {
                message="Account Info Is Updated In Database";
            }else{
                message="Info Is Not Updated  Due To "+action.getErrormessage();
            }
               CommonOperations.showScreen(getDesktopPane(), new ViewAccountType());
               dispose();
       }else{
               message="Invalid Operation";
                       
           }
           
       }
       JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed

    private void jtfAccountTypeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAccountTypeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAccountTypeIDActionPerformed

    private void jtfMinimumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMinimumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMinimumActionPerformed

    private void jtfInterestRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfInterestRateKeyTyped
        if(Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfInterestRateKeyTyped

    private void jtfAccountTypeIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAccountTypeIDKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfAccountTypeIDKeyTyped

    private void jtfAccountTypeNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfAccountTypeNameKeyTyped
        if(Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfAccountTypeNameKeyTyped

    private void jtfMinimumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMinimumKeyTyped
        if(Character.isAlphabetic(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtfMinimumKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfAccountTypeID;
    private javax.swing.JTextField jtfAccountTypeName;
    private javax.swing.JTextField jtfInterestRate;
    private javax.swing.JTextField jtfMinimum;
    // End of variables declaration//GEN-END:variables
}