package adminui;

import model.dao.*;
import model.to.*;
import utility.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ui.LoginFrame;


public class AdminMainScreen extends javax.swing.JFrame {
private String username;
    public AdminMainScreen() {
        try{
            ImageIcon icon;
            icon=new ImageIcon(getClass().getResource("/adminui/BANK.png"));
            setIconImage(icon.getImage());
        }catch(Exception ex) {}
        initComponents();
        setSize(1200,650);
        setLocationRelativeTo(null);
    }
    public AdminMainScreen(String username){
        this();
         this.username=username;
    }
        public void exit(){
            WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        }
        public void logout(){
           LoginFrame lf=new LoginFrame();
           lf.setVisible(true);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundDesktopPane21 = new adminui.BackgroundDesktopPane2();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmiAddNewAccountType = new javax.swing.JMenuItem();
        jmiViewAccountType = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiAddNewCompany = new javax.swing.JMenuItem();
        jmiViewCompany = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiAddNewBranch = new javax.swing.JMenuItem();
        jmiViewBranch = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiAddNewAccountInfo = new javax.swing.JMenuItem();
        jmiViewAccountInfo = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jmiAddNewProof = new javax.swing.JMenuItem();
        jmiViewProof = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmiAddNewAccountProof = new javax.swing.JMenuItem();
        jmiViewAccountProof = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jmiAddTransaction = new javax.swing.JMenuItem();
        jmiViewTransaction = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiViewAccountDetails = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiLogOut = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(backgroundDesktopPane21, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Account Type Operations");
        jMenu3.setBorderPainted(true);
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiAddNewAccountType.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiAddNewAccountType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add-64.png"))); // NOI18N
        jmiAddNewAccountType.setText("Add New Account Type Details");
        jmiAddNewAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewAccountTypeActionPerformed(evt);
            }
        });
        jMenu3.add(jmiAddNewAccountType);

        jmiViewAccountType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jmiViewAccountType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Search-64.png"))); // NOI18N
        jmiViewAccountType.setText("View Account Type Details");
        jmiViewAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewAccountTypeActionPerformed(evt);
            }
        });
        jMenu3.add(jmiViewAccountType);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Company Operations");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiAddNewCompany.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiAddNewCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add-64.png"))); // NOI18N
        jmiAddNewCompany.setText("Add New Company Details");
        jmiAddNewCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewCompanyActionPerformed(evt);
            }
        });
        jMenu4.add(jmiAddNewCompany);

        jmiViewCompany.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiViewCompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Search-64.png"))); // NOI18N
        jmiViewCompany.setText("View Company Details");
        jmiViewCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewCompanyActionPerformed(evt);
            }
        });
        jMenu4.add(jmiViewCompany);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Branch Operations");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiAddNewBranch.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiAddNewBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add-64.png"))); // NOI18N
        jmiAddNewBranch.setText("Add New Branch Details");
        jmiAddNewBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewBranchActionPerformed(evt);
            }
        });
        jMenu5.add(jmiAddNewBranch);

        jmiViewBranch.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiViewBranch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Search-64.png"))); // NOI18N
        jmiViewBranch.setText("View Branch Details");
        jmiViewBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewBranchActionPerformed(evt);
            }
        });
        jMenu5.add(jmiViewBranch);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Account Info Operations");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiAddNewAccountInfo.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiAddNewAccountInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add-64.png"))); // NOI18N
        jmiAddNewAccountInfo.setText("Add New Account Info Details");
        jmiAddNewAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewAccountInfoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiAddNewAccountInfo);

        jmiViewAccountInfo.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiViewAccountInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Search-64.png"))); // NOI18N
        jmiViewAccountInfo.setText("View Account Info Details");
        jmiViewAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewAccountInfoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiViewAccountInfo);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Proof Operations");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiAddNewProof.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiAddNewProof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add-64.png"))); // NOI18N
        jmiAddNewProof.setText("Add New Proof Details");
        jmiAddNewProof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewProofActionPerformed(evt);
            }
        });
        jMenu7.add(jmiAddNewProof);

        jmiViewProof.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiViewProof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Search-64.png"))); // NOI18N
        jmiViewProof.setText("View Proof Details");
        jmiViewProof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewProofActionPerformed(evt);
            }
        });
        jMenu7.add(jmiViewProof);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Account Proof Operations");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiAddNewAccountProof.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiAddNewAccountProof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add-64.png"))); // NOI18N
        jmiAddNewAccountProof.setText("Add New Account Proof Details");
        jmiAddNewAccountProof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddNewAccountProofActionPerformed(evt);
            }
        });
        jMenu8.add(jmiAddNewAccountProof);

        jmiViewAccountProof.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiViewAccountProof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Search-64.png"))); // NOI18N
        jmiViewAccountProof.setText("View Account Proof Details");
        jmiViewAccountProof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewAccountProofActionPerformed(evt);
            }
        });
        jMenu8.add(jmiViewAccountProof);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Transaction Operations");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiAddTransaction.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiAddTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add-64.png"))); // NOI18N
        jmiAddTransaction.setText("Add Transaction Details");
        jmiAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddTransactionActionPerformed(evt);
            }
        });
        jMenu9.add(jmiAddTransaction);

        jmiViewTransaction.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiViewTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Search-64.png"))); // NOI18N
        jmiViewTransaction.setText("View Transaction Details");
        jmiViewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewTransactionActionPerformed(evt);
            }
        });
        jMenu9.add(jmiViewTransaction);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Login Operation");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Add User Male-64.png"))); // NOI18N
        jMenuItem1.setText("Add New User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem1);

        jMenuBar1.add(jMenu10);

        jMenu2.setText("Report");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiViewAccountDetails.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiViewAccountDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Accounting-64.png"))); // NOI18N
        jmiViewAccountDetails.setText("View Account Details Report");
        jmiViewAccountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewAccountDetailsActionPerformed(evt);
            }
        });
        jMenu2.add(jmiViewAccountDetails);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("More");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiLogOut.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Logout Rounded Up-64.png"))); // NOI18N
        jmiLogOut.setText("Log Out");
        jmiLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLogOut);

        jmiExit.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/icons8-Exit-64.png"))); // NOI18N
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddNewAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewAccountTypeActionPerformed
        AddNewAccountType anat=new AddNewAccountType();
        CommonOperations.showScreen(backgroundDesktopPane21, anat);
    }//GEN-LAST:event_jmiAddNewAccountTypeActionPerformed

    private void jmiAddNewCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewCompanyActionPerformed
        AddNewCompany anc=new AddNewCompany();
        CommonOperations.showScreen(backgroundDesktopPane21, anc);
    }//GEN-LAST:event_jmiAddNewCompanyActionPerformed

    private void jmiAddNewBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewBranchActionPerformed
        AddNewBranch anb=new AddNewBranch();
       CommonOperations.showScreen(backgroundDesktopPane21, anb);
    }//GEN-LAST:event_jmiAddNewBranchActionPerformed

    private void jmiAddNewAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewAccountInfoActionPerformed
        AddNewAccountInfo anai=new AddNewAccountInfo();
       CommonOperations.showScreen(backgroundDesktopPane21, anai);
    }//GEN-LAST:event_jmiAddNewAccountInfoActionPerformed

    private void jmiAddNewProofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewProofActionPerformed
        AddNewProof ANP=new AddNewProof();
       CommonOperations.showScreen(backgroundDesktopPane21, ANP);
    }//GEN-LAST:event_jmiAddNewProofActionPerformed

    private void jmiAddNewAccountProofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddNewAccountProofActionPerformed
        AddNewAccountProof anap=new AddNewAccountProof();
       CommonOperations.showScreen(backgroundDesktopPane21, anap);
    }//GEN-LAST:event_jmiAddNewAccountProofActionPerformed

    private void jmiAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddTransactionActionPerformed
        AddNewTransaction ant=new AddNewTransaction();
        CommonOperations.showScreen(backgroundDesktopPane21, ant);
    }//GEN-LAST:event_jmiAddTransactionActionPerformed

    private void jmiViewAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewAccountTypeActionPerformed
        ViewAccountType vat=new ViewAccountType();
       CommonOperations.showScreen(backgroundDesktopPane21, vat);
    }//GEN-LAST:event_jmiViewAccountTypeActionPerformed

    private void jmiViewCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewCompanyActionPerformed
        ViewCompanyDetails vcd=new ViewCompanyDetails();
        CommonOperations.showScreen(backgroundDesktopPane21, vcd);
    }//GEN-LAST:event_jmiViewCompanyActionPerformed

    private void jmiViewBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewBranchActionPerformed
        ViewBranchDetails vbd=new ViewBranchDetails();
       CommonOperations.showScreen(backgroundDesktopPane21, vbd);
    }//GEN-LAST:event_jmiViewBranchActionPerformed

    private void jmiViewAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewAccountInfoActionPerformed
        ViewAccountInfo vai=new ViewAccountInfo();
        CommonOperations.showScreen(backgroundDesktopPane21, vai);
    }//GEN-LAST:event_jmiViewAccountInfoActionPerformed

    private void jmiViewProofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewProofActionPerformed
        ViewProofDetails vpd=new ViewProofDetails();
       CommonOperations.showScreen(backgroundDesktopPane21, vpd);
    }//GEN-LAST:event_jmiViewProofActionPerformed

    private void jmiViewAccountProofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewAccountProofActionPerformed
        ViewAccountProofDetails vapd=new ViewAccountProofDetails();
        CommonOperations.showScreen(backgroundDesktopPane21, vapd);
    }//GEN-LAST:event_jmiViewAccountProofActionPerformed

    private void jmiViewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewTransactionActionPerformed
        ViewTransactionDetails vtd=new ViewTransactionDetails();
        CommonOperations.showScreen(backgroundDesktopPane21, vtd);
    }//GEN-LAST:event_jmiViewTransactionActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
      int  result=JOptionPane.showConfirmDialog(this,"Are You Sure You Want To Exit ? ","Message From Admin",JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION){
            exit();
        }
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOutActionPerformed
         int  result=JOptionPane.showConfirmDialog(this,"Are You Sure You Want To Log Out ? ","Message From Admin",JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION){
            logout();
            dispose();
        }
    }//GEN-LAST:event_jmiLogOutActionPerformed

    private void jmiViewAccountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewAccountDetailsActionPerformed
        String path="F:/grapess/intrabankingg/build/classes/adminui/accountreport.jrxml";
        JasperReportGenerator jrg=new JasperReportGenerator(path);
        jrg.generateReport();
    }//GEN-LAST:event_jmiViewAccountDetailsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddNewUser anu=new AddNewUser();
        CommonOperations.showScreen(backgroundDesktopPane21, anu);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private adminui.BackgroundDesktopPane2 backgroundDesktopPane21;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmiAddNewAccountInfo;
    private javax.swing.JMenuItem jmiAddNewAccountProof;
    private javax.swing.JMenuItem jmiAddNewAccountType;
    private javax.swing.JMenuItem jmiAddNewBranch;
    private javax.swing.JMenuItem jmiAddNewCompany;
    private javax.swing.JMenuItem jmiAddNewProof;
    private javax.swing.JMenuItem jmiAddTransaction;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogOut;
    private javax.swing.JMenuItem jmiViewAccountDetails;
    private javax.swing.JMenuItem jmiViewAccountInfo;
    private javax.swing.JMenuItem jmiViewAccountProof;
    private javax.swing.JMenuItem jmiViewAccountType;
    private javax.swing.JMenuItem jmiViewBranch;
    private javax.swing.JMenuItem jmiViewCompany;
    private javax.swing.JMenuItem jmiViewProof;
    private javax.swing.JMenuItem jmiViewTransaction;
    // End of variables declaration//GEN-END:variables
}
