package adminui;

import model.dao.*;
import model.to.*;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

public class ViewCompanyDetails extends javax.swing.JInternalFrame {

    List<CompanyInfoTO> company;
    private JPopupMenu popup;
    private int row;

    public ViewCompanyDetails() {
        initComponents();
        bindTables();
        popup = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete This Record");
        JMenuItem edititem = new JMenuItem("Edit This Record");
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.setFont(new Font("Maiandra GD", Font.BOLD, 18));
        edititem.setFont(new Font("Maiandra GD", Font.BOLD, 18));
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/icons8-Trash-64.png"));
            deleteitem.setIcon(icon);
            icon = new ImageIcon(getClass().getResource("/adminui/icons8-Edit-64.png"));
            edititem.setIcon(icon);
        } catch (Exception ex) {
        }
        deleteitem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleterecord();
            }
        });
        edititem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editrecord();
            }
        });
        row = -1;
    }

    public void bindTables() {
        company = new CompanyInfoDAO().getAllRecord();
        String[] colnames = {"Company ID", "Company Name"};
        Object[][] records = null;
        if (company != null && company.size() > 0) {
            records = new Object[company.size()][colnames.length];
            int i = 0;
            for (CompanyInfoTO att : company) {
                records[i] = new Object[]{att.getCompanyid(), att.getCompanyname()};
                i++;
            }
        } else {
            records = new Object[1][colnames.length];
            records[0] = new Object[]{"No Record", "No Record"};
        }
        DefaultTableModel dtm = new DefaultTableModel(records, colnames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableCompanyDetails.getTableHeader().setReorderingAllowed(false);
        tableCompanyDetails.setAutoCreateRowSorter(true);
        tableCompanyDetails.setModel(dtm);
    }

    public void deleterecord() {
        if (row != -1 && company != null && row < company.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Delete This Record ?", "Message From Admin ", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                String message = "";
                CompanyInfoDAO action = new CompanyInfoDAO();
                CompanyInfoTO record = company.get(row);
                if (action.deleterecord(record.getCompanyid())) {
                    message = "Record Is Removed From Database";
                    bindTables();
                } else {
                    if (action.getErrormessage().contains("FOREIGN")) {
                        message = "This Account Is Enrolled By User. So Cannot Be Deleted";
                    } else {
                        message = "Deletion Failure Due To " + action.getErrormessage();
                    }
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        row = -1;
    }

    public void editrecord() {
        if (row != -1 && company != null && row < company.size()) {
            CompanyInfoTO record = company.get(row);
            CommonOperations.showScreen(getDesktopPane(), new AddNewCompany(record));
            dispose();
        }
        row = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompanyDetails = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Company Details");

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tableCompanyDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCompanyDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCompanyDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCompanyDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindTables();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableCompanyDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCompanyDetailsMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int rowpoint = tableCompanyDetails.rowAtPoint(evt.getPoint());
            tableCompanyDetails.getSelectionModel().setSelectionInterval(rowpoint, rowpoint);
            popup.show(tableCompanyDetails, evt.getX(), evt.getY());
            row = tableCompanyDetails.getSelectedRow();
        }
    }//GEN-LAST:event_tableCompanyDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCompanyDetails;
    // End of variables declaration//GEN-END:variables
}
