package adminui;

import model.dao.*;
import model.to.*;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

public class ViewAccountProofDetails extends javax.swing.JInternalFrame {

    List<AccountProofTO> accounts;
    private JPopupMenu popup;
    private int row;
    
    public ViewAccountProofDetails() {
        initComponents();
        bindTables();
        popup = new JPopupMenu();
        JMenuItem deleteitem = new JMenuItem("Delete This Record");
        JMenuItem edititem = new JMenuItem("Edit This Record");
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.setFont(new Font("Maiandra GD", Font.BOLD, 18));
        edititem.setFont(new Font("Maiandra GD", Font.BOLD, 18));
        try {
            ImageIcon icon;
            icon = new ImageIcon(getClass().getResource("/adminui/icons8-Trash-64.png"));
            deleteitem.setIcon(icon);
            icon = new ImageIcon(getClass().getResource("/adminui/icons8-Edit-64.png"));
            edititem.setIcon(icon);
        } catch (Exception ex) {
        }
        deleteitem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                deleterecord();
            }
        });
        edititem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                editrecord();
            }
        });
        row = -1;
    }
      public void bindTables() {
        accounts=new AccountProofDAO().getAllRecord();
        String[] colnames={"Srno","Proof ID","Account ID","Proof Value"};
        Object[][] records=null;
        if(accounts!=null  &&  accounts.size()>0) {
            records=new Object[accounts.size()][colnames.length];
            int i=0;
            for(AccountProofTO att:accounts){
                records[i]=new Object[]{att.getSrno(),att.getProofid(),att.getAccountid(),att.getProofvalue()};
                i++;
            }
        }else{
            records=new Object[1][colnames.length];
            records[0]=new Object[]{"No Record","No Record","No Record","No Record"};
                }
        DefaultTableModel dtm=new DefaultTableModel(records, colnames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tableAccountProof.getTableHeader().setReorderingAllowed(false);
        tableAccountProof.setAutoCreateRowSorter(true);
        tableAccountProof.setModel(dtm);
                }
       public void deleterecord() {
        if (row != -1 && accounts != null && row < accounts.size()) {
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Delete This Record ?", "Message From Admin ", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                String message = "";
                AccountProofDAO action = new AccountProofDAO();
                AccountProofTO record = accounts.get(row);
                if (action.deleterecord(String.valueOf(record.getSrno()))) {
                    message = "Record Is Removed From Database";
                    bindTables();
                } else {
                    if (action.getErrormessage().contains("FOREIGN")) {
                        message = "This Account Is Enrolled By User. So Cannot Be Deleted";
                    } else {
                        message = "Deletion Failure Due To " + action.getErrormessage();
                    }
                }
                JOptionPane.showMessageDialog(this, message);
            }
        }
        row = -1;
    }
       public void editrecord() {
        if (row != -1 && accounts != null && row < accounts.size()) {
            AccountProofTO record = accounts.get(row);
            CommonOperations.showScreen(getDesktopPane(), new AddNewAccountProof(record));
            dispose();
        }
        row = -1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccountProof = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Account Proof Details");

        tableAccountProof.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAccountProof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountProofMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccountProof);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindTables();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableAccountProofMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountProofMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            int rowpoint = tableAccountProof.rowAtPoint(evt.getPoint());
            tableAccountProof.getSelectionModel().setSelectionInterval(rowpoint, rowpoint);
            popup.show(tableAccountProof, evt.getX(), evt.getY());
            row = tableAccountProof.getSelectedRow();
        }
    }//GEN-LAST:event_tableAccountProofMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAccountProof;
    // End of variables declaration//GEN-END:variables
}
