package adminui;

import model.dao.*;
import model.to.*;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

public class ViewAccountInfo extends javax.swing.JInternalFrame {

    List<AccountInfoTO> account;
    private JPopupMenu popup;
    private int row;
    public ViewAccountInfo() {
        initComponents();
        bindTables();
        popup=new JPopupMenu();
        JMenuItem deleteitem=new JMenuItem("Delete This Record");
        JMenuItem edititem=new JMenuItem("Edit This Record");
        popup.add(deleteitem);
        popup.add(edititem);
        deleteitem.setFont(new Font("Maiandra GD", Font.BOLD, 18));
        edititem.setFont(new Font("Maiandra GD", Font.BOLD, 18));
        try{
            ImageIcon icon;
            icon=new ImageIcon(getClass().getResource("/adminui/icons8-Trash-64.png"));
            deleteitem.setIcon(icon);
            icon=new ImageIcon(getClass().getResource("/adminui/icons8-Edit-64.png"));
            edititem.setIcon(icon);
        }catch(Exception ex){
        }
            deleteitem.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                deleterecord();
                }
            });
            edititem.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                editrecord();
                }
            });
            row=-1;
    }
    public void bindTables() {
        account=new AccountInfoDAO().getAllRecord();
        String[] colnames={ "Account ID" , "Branch ID" , "Opening Date" , "Initial Balance" , "Current Balance" , "Name" , "Father Name" , "DOB" , "Contact No." , "Address" };
        Object[][] records=null;
        if(account!=null  &&  account.size()>0) {
            records=new Object[account.size()][colnames.length];
            int i=0; 
            for(AccountInfoTO att:account){
                records[i]=new Object[]{att.getAccountid(),att.getBranchid(),att.getOpeningdate(),att.getInitial_balance(),att.getCurrent_balance(),att.getName(),att.getFathername(),att.getDob(),att.getContactno(),att.getAddress()};
                i++;
            }
        }else{
            records=new Object[1][colnames.length];
            records[0]=new Object[]{ "No Record","No Record","No Record","No Record","No Record","No Record","No Record","No Record","No Record","No Record" };
                }
        DefaultTableModel dtm=new DefaultTableModel(records, colnames) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        tableAccountInfo.getTableHeader().setReorderingAllowed(false);
        tableAccountInfo.setAutoCreateRowSorter(true);
        tableAccountInfo.setModel(dtm);
                }
   public void deleterecord(){
       if(row!=-1 && account!=null && row<account.size()){
          int result= JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Delete This Record ?", "Message From Admin ",JOptionPane.YES_NO_OPTION);
          if(result==JOptionPane.YES_OPTION){
              String message="";
              AccountInfoDAO action=new AccountInfoDAO();
              AccountInfoTO record=account.get(row);
              if(action.deleterecord(record.getAccountid())){
                  message="Record Is Removed From Databse";
                  bindTables();
              }else{
                  if(action.getErrormessage().contains("FOREIGN")){
                      message="This Account Is Enrolled By User. So Cannot Be Deleted";
                  }else{
                  message="Deletion Failure Due To " + action.getErrormessage();
              }
              }
              JOptionPane.showMessageDialog(this, message);
          }
       }
       row=-1;
   }
    public void editrecord(){
       if(row!=-1 && account!=null && row<account.size()){
           AccountInfoTO record=account.get(row);
           CommonOperations.showScreen(getDesktopPane(),new AddNewAccountInfo(record));
           dispose();
       }
       row=-1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccountInfo = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("View Account Info Details");

        tableAccountInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAccountInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAccountInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAccountInfo);

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        bindTables();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableAccountInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAccountInfoMouseClicked
        if(evt.getButton()==MouseEvent.BUTTON3){
            int rowpoint=tableAccountInfo.rowAtPoint(evt.getPoint());
            tableAccountInfo.getSelectionModel().setSelectionInterval(rowpoint,rowpoint);
            popup.show(tableAccountInfo,evt.getX(),evt.getY());
            row=tableAccountInfo.getSelectedRow();
        }
    }//GEN-LAST:event_tableAccountInfoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAccountInfo;
    // End of variables declaration//GEN-END:variables
}
